#!/usr/bin/python3
#-*-python-*-##################################################################
# Copyright 2021-2022 Inesonic, LLC
# All Rights Reserved
###############################################################################

"""
Python command-line tool to test and demonstrate the /v1/events/create endpoint
and associated Python API functions.

"""

###############################################################################
# Import:
#

import sys
import argparse
import json

import speedsentry

###############################################################################
# Globals:
#

VERSION = "1a"
"""
The tool version number.

"""

DESCRIPTION = """
Copyright 2021-2022 Inesonic, LLC

You can use this small command line tool to demonstrate the
/v1/events/create REST API endpoint.

"""

###############################################################################
# Main:
#

command_line_parser = argparse.ArgumentParser(description = DESCRIPTION)

command_line_parser.add_argument(
    "-v",
    "--version",
    action = 'version',
    version = VERSION
)

command_line_parser.add_argument(
    "-i",
    "--id",
    help = "You can use this switch to specify the customer identifier.",
    type = str,
    dest = 'customer_identifier'
)

command_line_parser.add_argument(
    "-s",
    "--secret",
    help = "You can use this switch to specify the customer secret.  "
           "The provided secret should be base-64 encoded.",
    type = str,
    dest = 'customer_secret'
)

command_line_parser.add_argument(
    "-m",
    "--message",
    help = "You can use this switch to specify the message to be sent.",
    type = str,
    dest = 'message'
)

command_line_parser.add_argument(
    "-M",
    "--monitor-id",
    help = "You can use this switch to specify the monitor ID of the monitor "
           "to tie to this message.",
    type = int,
    default = None,
    dest = 'monitor_id'
)

command_line_parser.add_argument(
    "-t",
    "--type",
    help = "You can use this switch to specify the custom event type.  Value "
           "should be an integer between 1 and 10.  If not specified, then 1 "
           "is used.",
    type = int,
    default = 1,
    dest = 'type_index'
)

arguments = command_line_parser.parse_args()
customer_identifier = arguments.customer_identifier
customer_secret = arguments.customer_secret
message = arguments.message
monitor_id = arguments.monitor_id
type_index = arguments.type_index

api = speedsentry.SpeedSentry(
    customer_identifier = customer_identifier,
    customer_secret = customer_secret
)

api.events_create(
    message = message,
    type_index = type_index,
    monitor_id = monitor_id
)
